IF OBJECT_ID('dbo.GSTType') IS NOT NULL
BEGIN
    DROP TABLE dbo.GSTType
    IF OBJECT_ID('dbo.GSTType') IS NOT NULL
        PRINT '<<< FAILED DROPPING TABLE dbo.GSTType >>>'
    ELSE
        PRINT '<<< DROPPED TABLE dbo.GSTType >>>'
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE TABLE [dbo].[GSTType](
	[GSTTypeID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[GSTTypeCode] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](200) NULL,
	[SortOrder] [int] NOT NULL,
	[CreateBy] [uniqueidentifier] NULL,
	[CreateDate] [datetime] NULL,
 CONSTRAINT [PK_GSTType] PRIMARY KEY CLUSTERED 
(
	[GSTTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[GSTType] ADD  CONSTRAINT [DF_GSTType_GSTTypeID]  DEFAULT (newid()) FOR [GSTTypeID]
GO


SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
IF OBJECT_ID('dbo.GSTType') IS NOT NULL
    PRINT '<<< CREATED TABLE dbo.GSTType >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE dbo.GSTType >>>'
GO